name: CI

on: [push]

jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Respoitory
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Teste
        run: yarn test

      - name: Build
        run: yarn build
