name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node-version }}
        run: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i -g yarn
      - run: yarn install

      - name: Linting
        run: yarn lint

      - name: Teste
        run: yarn test

      - name: Linting
        run: yarn build
