name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        run: actions/setup-node@v1

      - name: Install dependencies
        run: npm i -g yarn
      - run: yarn install

      - name: Linting
        run: yarn lint

      - name: Teste
        run: yarn test

      - name: Linting
        run: yarn build
